/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockLendingPool__factory } from "./MockLendingPool__factory";
export { MockToken__factory } from "./MockToken__factory";
